### ISSUE TITLE
Wrong Relationship Type in *.rels 

### ISSUE THREAD

**Issue by FrankSchnicke** [admin-shell-io/aas-test-engines#2]
The testing tool is using "http://www.admin-shell.io/aasx/relationships" as namespace for relations. However, according to the [AASX specification](https://industrialdigitaltwin.org/wp-content/uploads/2023/04/IDTA-01005-3-0_SpecificationAssetAdministrationShell_Part5_AASXPackageFileFormat.pdf) on p. 17, it should be "http://admin-shell.io/aasx/relationships" (note the missing "www"). This is also implemented wrong in the AASX Package Explorer (cf. https://github.com/admin-shell-io/aasx-package-explorer/issues/666 as well as in AAS4J (cf. https://github.com/eclipse-aas4j/aas4j/issues/202).

**Comment by FrankSchnicke** [comment]
Is there any update on this? As of today, it is still not fixed if I'm not missing something.

**Comment by otto-ifak** [comment]
I am very sorry for the late response. We had a short discussion about this, as many people are using the Package Explorer and expect it to generate valid AAS files. Additionally, we have to change the acceptance tests as these are wrong, too.
In the end you are definitely right so that we scheduled the fix for next week. I will update this issue accordingly, then.
