### ISSUE TITLE
Which AAS Specification version(s) and/or releases are supported?

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-test-engines#9]
From the Readme it seems API  version 1.0RC03  is supported?

How would you notify which test engine is valid for which version or does one and the same test engine support or will support more than one version?  How do I select the version required when calling the test engine?

**Comment by otto-ifak** [comment]
Hi @BirgitBoss, this was actually an error in the README, 1.0RC03 is not supported (anymore).
This mistake has been fixed in 9657296566e60ee8ab5c6ba039b60d8588cc9bec.

Each release of the test engine will support the current version and the one before the current. It might include support for older versions as well, but most probably we will not fix any bugs for these anymore.

For certification, you will always have to use the most recent version of the test engine. You can only select the version of the specification you want to check against.
